name: Pulumi
on:
  push:
    branches:
      - master
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - name: Create temporary folder
        run: mkdir temp

      - name: Checkout your repository
        uses: actions/checkout@v2

      - name: Checkout durgap09/pulumi-files-WFGA repository
        uses: actions/checkout@v2
        with:
          repository: durgap09/pulumi-files-WFGA
          ref: main
          path: temp-files

      - name: Copy files to temp folder
        run: cp -R temp-files/* .

      - name: Set AWS Region
        run: echo "AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Verify contents of working directory
        run: ls -l

      - name: Install Dependencies
        run: npm install



      - name: Pulumi Preview
        uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      
        
