name: Pulumi

on:
  push:
    branches:
      - 'dp-git'  # Trigger the workflow when pushing to the 'main' branch

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest

    steps:
      - name: Create temporary folder
        run: mkdir temp

      - name: Checkout your repository
        uses: actions/checkout@v2

      - name: Checkout durgap09/pulumi-files-WFGA repository
        uses: actions/checkout@v2
        with:
          repository: durgap09/pulumi-files-WFGA
          ref: main
          path: temp-files

      - name: Copy files to temp folder
        run: cp -R temp-files/* .

      - name: Set AWS Region
        run: echo "AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Set PULUMI_ORG_NAME
        run: |
          PULUMI_ORG_NAME=$(echo ${{ github.ref }} | awk -F'/' '{print $3}')
          echo "PULUMI_ORG_NAME=$PULUMI_ORG_NAME" >> $GITHUB_ENV

      - name: Set PULUMI_STACK_NAME
        run: |
          PULUMI_STACK_NAME=$(echo ${{ github.ref }} | awk -F'/' '{print $NF}')
          echo "PULUMI_STACK_NAME=$PULUMI_STACK_NAME" >> $GITHUB_ENV

      - name: Touch Pulumi.yaml
        run: touch Pulumi.yaml

      - name: Create Pulumi.yaml
        run: |
          echo "name: ${{ env.PULUMI_ORG_NAME }}" > Pulumi.yaml
          echo "runtime:" >> Pulumi.yaml
          echo "  name: nodejs" >> Pulumi.yaml
          echo "  options:" >> Pulumi.yaml
          echo "    typescript: false" >> Pulumi.yaml
          echo "description: A minimal AWS JavaScript Pulumi program" >> Pulumi.yaml

      - name: Install Dependencies
        run: npm install

      - name: Pulumi Preview
        uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: ${{ env.PULUMI_STACK_NAME }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: Pulumi UP
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: ${{ env.PULUMI_STACK_NAME }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
